stages:
  - test

variables:
  GIT_DEPTH:                       3
  REGISTRY:                        "registry.parity.io/parity/infrastructure/scripts"

image:                             ${REGISTRY}/parity-ci-docs:latest

cache:
  key: '${CI_JOB_NAME}'
  paths:
    - node_modules/

linux-test:
  stage: test
  image: node:12
  script:
    - yarn test
    - yarn lint
  tags:
    - linux-docker
